apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application #Como se va a llamar mi app en argo
  namespace: openshift-gitops #nomobre del ns del operador
spec:
  project: default

  source:
    repoURL: https://github.com/DavePool/argoCICD.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

#Warning, esta opción no es recomendada ya que siempre va a estar checando los cambios en el repo de git y los aplicara de inmediato 
    automated:
      selfHeal: true
      prune: true

